tap "FelixKratz/formulae"

brew "borders"
brew "chafa"
brew "direnv"
brew "elixir"
brew "erlang"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "lazygit"
brew "mise"
brew "neovim"
brew "nvm"
brew "opencode"
brew "postgresql@14"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "yazi"
brew "zoxide"
brew "zsh"

cask "font-jetbrains-mono-nerd-font"
cask "nikitabobko/tap/aerospace"
cask "ghostty"
