# Defaults
set -ga terminal-overrides ",*:RGB"
set -g default-terminal "tmux-256color"
set -g base-index 1
set -g pane-base-index 1
set -g mouse on

set -g set-clipboard on
# Leader
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Panes
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind _ split-window -v -c "#{pane_current_path}"

# Reload
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Navigation
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

set-window-option -g mode-keys vi
unbind -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind -n C-1 select-window -t 1
bind -n C-2 select-window -t 2
bind -n C-3 select-window -t 3
bind -n C-4 select-window -t 4
bind -n C-5 select-window -t 5
bind -n C-6 select-window -t 6
bind -n C-7 select-window -t 7
bind -n C-8 select-window -t 8
bind -n C-9 select-window -t 9

# Theming
set -g status-position top
set -g status-style 'bg=default,fg=white'
set -g status-left ''
set -g status-right '#[fg=brightwhite,bold] #S '
set -g status-right-length 50
set -g window-status-format '#[fg=gray] #I:#W '
set -g window-status-current-format '#[fg=green,bold] #I:#W '
set -g window-status-separator ''

# Plugins (installed to ~/.tmux/plugins/, not dotfiles)
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Resurrect & Continuum config
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'

# Initialize TPM (must be at the bottom)
run '~/.tmux/plugins/tpm/tpm'
