return {
  -- "hrsh7th/nvim-cmp",
  -- lazy = false, -- force eager load
  -- priority = 1000, -- load before LSP plugins
  -- dependencies = {
  --   "hrsh7th/cmp-nvim-lsp",
  --   "hrsh7th/cmp-buffer",
  --   "hrsh7th/cmp-path",
  --   "hrsh7th/cmp-emoji",
  --   -- add more sources as needed
  -- },
  -- opts = function(_, opts)
  --   local cmp = require("cmp")
  --   opts.mapping = vim.tbl_extend("force", opts.mapping, {
  --     ["<CR>"] = cmp.mapping.confirm({ select = true }),
  --     ["<Tab>"] = cmp.mapping.select_next_item(),
  --     ["<S-Tab>"] = cmp.mapping.select_prev_item(),
  --   })
  --   table.insert(opts.sources, { name = "emoji" })
  --   -- Add copilot as a source at the top if copilot-cmp is installed
  --   if pcall(require, "copilot_cmp") then
  --     table.insert(opts.sources, 1, { name = "copilot" })
  --   end
  -- end,
}
